spark.eventLog.enabled           true
spark.eventLog.dir               file:///opt/spark/spark-events
spark.history.fs.logDirectory    file:///opt/spark/spark-events

# Thrift Server / Hive metastore (in-memory Derby for read-only catalogs)
spark.sql.warehouse.dir                                    /tmp/spark-warehouse
spark.hadoop.javax.jdo.option.ConnectionURL                jdbc:derby:memory:metastore_db;create=true
spark.hadoop.javax.jdo.option.ConnectionDriverName         org.apache.derby.jdbc.EmbeddedDriver