# spark-defaults.conf of a Thrift or Connect server
spark.jars.packages               io.github.neutrinic:apilytics_2.13:1.0.1
spark.sql.catalog.api             com.apilytics.spark.RESTCatalog
spark.sql.catalog.api.config      /etc/apilytics/api.conf
